"""
AI text detection service using local Ollama LLM.

This service uses a local LLM (mistral) via Ollama
to detect whether text is AI-generated or human-written based on writing style.
"""

import json
import re
from typing import Dict

import requests

from ..config import OLLAMA_MODEL, OLLAMA_URL
from ..models.schemas import AIDetectionRequest, AIDetectionResponse


class AIDetectionService:
    """Service for detecting AI-generated text using local LLM."""

    def __init__(self):
        """Initialize the AI detection service with LLM support."""
        print("AI Detection service initialized with Ollama LLM support (mistral)")

    def detect_ai_text(self, request: AIDetectionRequest) -> AIDetectionResponse:
        """
        Detect if text is AI-generated or human-written using LLM classification.

        Args:
            request: AIDetectionRequest with text to analyze

        Returns:
            AIDetectionResponse with probabilities and classification

        The detection process:
        1. Send text to Ollama LLM with classification prompt
        2. Parse structured JSON response
        3. Return probability scores and confidence level
        """

        def _coerce_number(value):
            """Coerce a value into a float in [0, 100] when possible."""
            if isinstance(value, (int, float)):
                num = float(value)
            elif isinstance(value, str):
                cleaned = value.strip().replace("%", "")
                m = re.search(r"[-+]?\d*\.?\d+", cleaned)
                if not m:
                    raise ValueError(f"Invalid numeric value: {value}")
                num = float(m.group())
            else:
                raise ValueError(f"Invalid numeric type: {type(value)}")

            return max(0.0, min(100.0, num))

        def _normalize_label(value: str) -> str:
            v = str(value).strip().lower()
            if v in ["ai", "a.i.", "ai-generated", "ai generated", "generated", "machine"]:
                return "AI"
            if v in ["human", "human-written", "human written", "person", "person-written"]:
                return "Human"
            return "Human"

        def _normalize_confidence(value: str) -> str:
            v = str(value).strip().lower()
            if v.startswith("h"):
                return "High"
            if v.startswith("m"):
                return "Medium"
            if v.startswith("l"):
                return "Low"
            return "Medium"

        def _try_parse_json_candidates(text: str) -> Dict:
            """
            LLMs sometimes wrap JSON in prose or return slightly invalid JSON.
            Try a few extraction strategies and parse the first valid object.
            """
            if not text or not text.strip():
                raise ValueError("Empty LLM response")

            candidates = []
            candidates.extend(re.findall(r"\{[\s\S]*?\}", text))

            start = text.find("{")
            end = text.rfind("}")
            if start != -1 and end != -1 and end > start:
                candidates.append(text[start : end + 1])

            def _sanitize(s: str) -> str:
                s2 = s.strip()
                if "'" in s2 and '"' not in s2:
                    s2 = s2.replace("'", '"')
                s2 = re.sub(r",(\s*[}\]])", r"\1", s2)
                return s2

            last_err = None
            for candidate in candidates:
                try:
                    return json.loads(_sanitize(candidate))
                except Exception as e:
                    last_err = e
                    continue

            raise ValueError(f"Invalid JSON response from LLM: {last_err}")

        def _call_ollama_and_parse(req: AIDetectionRequest) -> Dict:
            """
            Call Ollama once and parse the JSON response.

            Raises:
              - ConnectionError for connectivity/LLM issues
              - RuntimeError for non-200 statuses (non-CUDA errors)
              - ValueError for JSON/formatting issues
            """
            prompt = f"""You are an AI text detection expert.

Analyze whether the following text was written by a human or generated by an AI model.

Consider these signals:
- repetitive phrasing
- overly perfect grammar
- predictable sentence patterns
- lack of personal tone
- unnatural fluency

Language: {req.language}

Return ONLY valid JSON:

{{
  "ai_probability": number between 0 and 100,
  "human_probability": number between 0 and 100,
  "label": "AI" or "Human",
  "confidence": "Low | Medium | High"
}}

Text:
\"\"\"{req.text}\"\"\""""

            payload = {
                "model": OLLAMA_MODEL,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.0,
                    "top_p": 0.9,
                },
            }

            try:
                response = requests.post(
                    f"{OLLAMA_URL}/api/generate",
                    json=payload,
                    timeout=110,
                )
            except requests.exceptions.RequestException as e:
                # Normalize transport errors so the router can map to HTTP 503.
                raise ConnectionError("LLM service unavailable") from e

            if response.status_code != 200:
                err_text = (response.text or "").lower()
                if "cuda error" in err_text or "runner process has terminated" in err_text:
                    raise ConnectionError("LLM service unavailable")
                raise RuntimeError(f"Ollama returned status {response.status_code}: {response.text}")

            data = response.json()
            response_text = data.get("response", "")
            return _try_parse_json_candidates(response_text)

        try:
            result = _call_ollama_and_parse(request)
        except ValueError:
            try:
                result = _call_ollama_and_parse(request)
            except ValueError as e:
                raise ValueError("DETECTION_FAILED") from e

        required_fields = ["ai_probability", "human_probability", "label", "confidence"]
        for field in required_fields:
            if field not in result:
                raise ValueError(f"Missing required field '{field}' in LLM response")

        ai_prob = _coerce_number(result["ai_probability"])
        human_prob = _coerce_number(result["human_probability"])

        total = ai_prob + human_prob
        if total > 0 and (total < 95 or total > 105):
            ai_prob = (ai_prob / total) * 100.0
            human_prob = 100.0 - ai_prob

        label = _normalize_label(result["label"])
        confidence = _normalize_confidence(result["confidence"])

        return AIDetectionResponse(
            success=True,
            aiProbability=ai_prob,
            humanProbability=human_prob,
            label=label,
            confidence=confidence,
        )


# Global service instance
ai_detection_service = AIDetectionService()

